from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict, List

import pandas as pd

from src.export.compute_nardini90_features import (
    compositional_feature_names,
    compositional_features,
    patterning_36_features,
    patterning_feature_names,
    sanitize_sequence,
)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Compute NARDINI90 features for IUPred-defined IDR segments of TAIR proteins."
    )
    parser.add_argument(
        "--input-tsv",
        default="data/validation/tair_idr_regions.tsv",
        help="TSV with columns: tair_id, idr_seq (and optionally idr_start/idr_end).",
    )
    parser.add_argument(
        "--output-tsv",
        default="data/validation/tair_idr_nardini90.tsv",
        help="Output TSV with tair_id, IDR info and 90 NARDINI features.",
    )
    parser.add_argument(
        "--num-scrambles",
        type=int,
        default=30,
        help="Number of scrambles for patterning features (consistent with TAIR full-length).",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=7,
        help="Base random seed for patterning scrambles.",
    )
    args = parser.parse_args()

    root = Path(__file__).resolve().parents[2]
    in_path = root / args.input_tsv
    out_path = root / args.output_tsv
    out_path.parent.mkdir(parents=True, exist_ok=True)

    print(f"Reading TAIR IDR regions from: {in_path}")
    idr_df = pd.read_csv(in_path, sep="\t")

    if "tair_id" not in idr_df.columns or "idr_seq" not in idr_df.columns:
        raise ValueError(
            "Expected columns 'tair_id' and 'idr_seq' in input TSV "
            "(generated by parse_iupred_long_to_idr.py)."
        )

    before = len(idr_df)
    idr_df["idr_seq_clean"] = idr_df["idr_seq"].fillna("").map(sanitize_sequence)
    idr_df = idr_df[idr_df["idr_seq_clean"].str.len() > 0].reset_index(drop=True)
    print(f"Total IDR segments: {before}, valid after sanitization: {len(idr_df)}")
    if idr_df.empty:
        raise RuntimeError("No valid IDR segments after sanitization.")

    # Load compositional z-score stats from training set
    stats_path = root / "data" / "processed" / "nardini90_comp_zstats.tsv"
    print(f"Loading compositional z-score stats from: {stats_path}")
    stats_df = pd.read_csv(stats_path, sep="\t")

    comp_names = compositional_feature_names()
    pat_names = patterning_feature_names()
    all_feature_names = comp_names + pat_names

    stats_df = stats_df.set_index("feature")
    means = stats_df["mean"].to_dict()
    stds = stats_df["std"].to_dict()

    print(f"Computing compositional features for {len(idr_df)} IDR segments ...")
    raw_comp: List[List[float]] = [
        compositional_features(seq) for seq in idr_df["idr_seq_clean"]
    ]

    z_comp_rows: List[List[float]] = []
    for row_vals in raw_comp:
        z_row: List[float] = []
        for feat, val in zip(comp_names, row_vals):
            mu = means.get(feat, 0.0)
            sd = stds.get(feat, 1.0)
            if sd <= 0:
                z_val = 0.0
            else:
                z_val = (val - mu) / sd
            z_row.append(float(z_val))
        z_comp_rows.append(z_row)

    rows_out: List[Dict[str, object]] = []
    print("Computing patterning features and assembling NARDINI90 matrix for IDRs ...")
    for idx, (row, z_comp) in enumerate(
        zip(idr_df.to_dict(orient="records"), z_comp_rows), start=0
    ):
        seq = row["idr_seq_clean"]
        pat = patterning_36_features(
            seq,
            num_scrambles=args.num_scrambles,
            seed=args.seed + idx,
        )
        vals = z_comp + pat
        out_row: Dict[str, object] = {
            "tair_id": row["tair_id"],
        }
        # Preserve region metadata if present
        for col in ["idr_index", "idr_start", "idr_end", "idr_length", "mean_score", "max_score"]:
            if col in row:
                out_row[col] = row[col]
        for name, val in zip(all_feature_names, vals):
            out_row[name] = float(val)
        rows_out.append(out_row)
        if (idx + 1) % 20 == 0:
            print(f"  Processed {idx + 1} / {len(idr_df)} IDR segments")

    out_df = pd.DataFrame(rows_out)
    out_df.to_csv(out_path, sep="\t", index=False)
    print(
        f"Wrote NARDINI90 features for {len(out_df)} TAIR IDR segments "
        f"to {out_path}"
    )


if __name__ == "__main__":
    main()

