from __future__ import annotations

import argparse
from pathlib import Path
from typing import Dict, List

import pandas as pd

from src.export.compute_nardini90_features import (
    compositional_feature_names,
    compositional_features,
    patterning_36_features,
    patterning_feature_names,
    sanitize_sequence,
)


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Compute NARDINI90 features for TAIR proteins by "
            "concatenating all their IDR segments (one feature vector per protein)."
        )
    )
    parser.add_argument(
        "--input-tsv",
        default="data/validation/tair_idr_regions.tsv",
        help="TSV with columns: tair_id, idr_seq, idr_start, idr_end, idr_length.",
    )
    parser.add_argument(
        "--output-tsv",
        default="data/validation/tair_idr_concat_nardini90.tsv",
        help="Output TSV with one row per tair_id and 90 NARDINI features.",
    )
    parser.add_argument(
        "--num-scrambles",
        type=int,
        default=30,
        help="Number of scrambles for patterning features (consistent with TAIR full-length).",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=7,
        help="Base random seed for patterning scrambles.",
    )
    args = parser.parse_args()

    root = Path(__file__).resolve().parents[2]
    in_path = root / args.input_tsv
    out_path = root / args.output_tsv
    out_path.parent.mkdir(parents=True, exist_ok=True)

    print(f"Reading TAIR IDR regions from: {in_path}")
    idr_df = pd.read_csv(in_path, sep="\t")

    if "tair_id" not in idr_df.columns or "idr_seq" not in idr_df.columns:
        raise ValueError(
            "Expected columns 'tair_id' and 'idr_seq' in input TSV "
            "(generated by fetch_tair_idr_from_mobidb.py or similar)."
        )

    # Clean each IDR segment sequence
    idr_df["idr_seq_clean"] = idr_df["idr_seq"].fillna("").map(sanitize_sequence)
    idr_df = idr_df[idr_df["idr_seq_clean"].str.len() > 0].reset_index(drop=True)
    print(
        f"Total IDR segments: {len(idr_df)}, "
        f"TAIR with at least one valid IDR: {idr_df['tair_id'].nunique()}"
    )
    if idr_df.empty:
        raise RuntimeError("No valid IDR segments after sanitization.")

    # Concatenate all IDR segments per protein, ordered by start position if available
    print("Concatenating IDR segments per TAIR protein ...")
    if "idr_start" in idr_df.columns and "idr_end" in idr_df.columns:
        idr_df = idr_df.sort_values(["tair_id", "idr_start", "idr_end"])
    else:
        idr_df = idr_df.sort_values(["tair_id"])

    grouped = []
    for tid, sub in idr_df.groupby("tair_id", sort=False):
        concat_seq = "".join(sub["idr_seq_clean"].tolist())
        if not concat_seq:
            continue
        total_len = int(sub.get("idr_length", sub["idr_seq_clean"].str.len()).sum())
        n_segs = len(sub)
        grouped.append(
            {
                "tair_id": tid,
                "idr_concat_seq": concat_seq,
                "idr_total_length": total_len,
                "idr_num_segments": n_segs,
            }
        )

    prot_df = pd.DataFrame(grouped)
    print(
        f"Proteins with concatenated IDR sequence: {len(prot_df)} "
        f"(out of {idr_df['tair_id'].nunique()} with any IDR)"
    )
    if prot_df.empty:
        raise RuntimeError("No proteins with concatenated IDR sequences.")

    # Load compositional z-score stats from training set
    stats_path = root / "data" / "processed" / "nardini90_comp_zstats.tsv"
    print(f"Loading compositional z-score stats from: {stats_path}")
    stats_df = pd.read_csv(stats_path, sep="\t")

    comp_names = compositional_feature_names()
    pat_names = patterning_feature_names()
    all_feature_names = comp_names + pat_names

    stats_df = stats_df.set_index("feature")
    means = stats_df["mean"].to_dict()
    stds = stats_df["std"].to_dict()

    print(
        f"Computing compositional features for {len(prot_df)} concatenated IDR sequences ..."
    )
    raw_comp: List[List[float]] = [
        compositional_features(seq) for seq in prot_df["idr_concat_seq"]
    ]

    z_comp_rows: List[List[float]] = []
    for row_vals in raw_comp:
        z_row: List[float] = []
        for feat, val in zip(comp_names, row_vals):
            mu = means.get(feat, 0.0)
            sd = stds.get(feat, 1.0)
            if sd <= 0:
                z_val = 0.0
            else:
                z_val = (val - mu) / sd
            z_row.append(float(z_val))
        z_comp_rows.append(z_row)

    rows_out: List[Dict[str, object]] = []
    print(
        "Computing patterning features and assembling NARDINI90 matrix "
        "for concatenated IDRs ..."
    )
    for idx, (row, z_comp) in enumerate(
        zip(prot_df.to_dict(orient="records"), z_comp_rows), start=0
    ):
        seq = row["idr_concat_seq"]
        pat = patterning_36_features(
            seq,
            num_scrambles=args.num_scrambles,
            seed=args.seed + idx,
        )
        vals = z_comp + pat
        out_row: Dict[str, object] = {
            "tair_id": row["tair_id"],
            "idr_total_length": row["idr_total_length"],
            "idr_num_segments": row["idr_num_segments"],
        }
        for name, val in zip(all_feature_names, vals):
            out_row[name] = float(val)
        rows_out.append(out_row)
        if (idx + 1) % 20 == 0:
            print(f"  Processed {idx + 1} / {len(prot_df)} proteins")

    out_df = pd.DataFrame(rows_out)
    out_df.to_csv(out_path, sep="\t", index=False)
    print(
        f"Wrote NARDINI90 features for {len(out_df)} TAIR proteins "
        f"(concatenated IDRs) to {out_path}"
    )


if __name__ == "__main__":
    main()

